In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv("Dataset/BarcaMaster.csv")

In [3]:
matches

          Date Location            Opponent  Goal_For  Goal_Against  Result
0    18/8/2018     Home    Deportivo Alavés         3             0     NaN
1    25/8/2018     Away  Real Valladolid CF         1             0     NaN
2     2/9/2018     Home           SD Huesca         8             2     NaN
3    15/9/2018     Away       Real Sociedad         2             1     NaN
4    23/9/2018     Home           Girona FC         2             2     NaN
..         ...      ...                 ...       ...           ...     ...
185  14/5/2023     Away        RCD Espanyol         4             2     NaN
186  20/5/2023     Home       Real Sociedad         1             2     NaN
187  23/5/2023     Away  Real Valladolid CF         1             3     NaN
188  28/5/2023     Home        RCD Mallorca         3             0     NaN
189   4/6/2023     Away            RC Celta         1             2     NaN

[190 rows x 6 columns]

In [4]:
# create a list of our conditions
conditions = [
    (matches['Goal_For'] > matches['Goal_Against']),
    (matches['Goal_For'] < matches['Goal_Against']),
    (matches['Goal_For'] == matches['Goal_Against'])
    ]

# create a list of the values we want to assign for each condition
values = ['W', 'L', 'D']

# create a new column and use np.select to assign values to it using our lists as arguments
matches['Result'] = np.select(conditions, values)

# display updated DataFrame
matches

          Date Location            Opponent  Goal_For  Goal_Against Result
0    18/8/2018     Home    Deportivo Alavés         3             0      W
1    25/8/2018     Away  Real Valladolid CF         1             0      W
2     2/9/2018     Home           SD Huesca         8             2      W
3    15/9/2018     Away       Real Sociedad         2             1      W
4    23/9/2018     Home           Girona FC         2             2      D
..         ...      ...                 ...       ...           ...    ...
185  14/5/2023     Away        RCD Espanyol         4             2      W
186  20/5/2023     Home       Real Sociedad         1             2      L
187  23/5/2023     Away  Real Valladolid CF         1             3      L
188  28/5/2023     Home        RCD Mallorca         3             0      W
189   4/6/2023     Away            RC Celta         1             2      L

[190 rows x 6 columns]

In [5]:
# file_path = 'Dataset/Barca_Master_new.csv'
# matches.to_csv(file_path, index=False)

In [6]:
matches.dtypes

Date            object
Location        object
Opponent        object
Goal_For         int64
Goal_Against     int64
Result          object
dtype: object

In [7]:
matches["Date"] = pd.to_datetime(matches["Date"])

/var/folders/j3/tmy3wxks75ng_bwdfzygm2fh0000gn/T/ipykernel_8305/254043194.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  matches["Date"] = pd.to_datetime(matches["Date"])

In [8]:
matches.dtypes

Date            datetime64[ns]
Location                object
Opponent                object
Goal_For                 int64
Goal_Against             int64
Result                  object
dtype: object

In [9]:
matches["Venue_code"] = matches["Location"].astype("category").cat.codes

In [10]:
matches

,Date,Location,Opponent,Goal_For,Goal_Against,Result,Venue_code
0,2018-08-18,Home,Deportivo Alavés,3,0,W,1
1,2018-08-25,Away,Real Valladolid CF,1,0,W,0
2,2018-02-09,Home,SD Huesca,8,2,W,1
3,2018-09-15,Away,Real Sociedad,2,1,W,0
4,2018-09-23,Home,Girona FC,2,2,D,1
...,...,...,...,...,...,...,...
185,2023-05-14,Away,RCD Espanyol,4,2,W,0
186,2023-05-20,Home,Real Sociedad,1,2,L,1
187,2023-05-23,Away,Real Valladolid CF,1,3,L,0
188,2023-05-28,Home,RCD Mallorca,3,0,W,1
189,2023-04-06,Away,RC Celta,1,2,L,0

In [11]:
matches["opp_code"] = matches["Opponent"].astype("category").cat.codes

In [12]:
matches

,Date,Location,Opponent,Goal_For,Goal_Against,Result,Venue_code,opp_code
0,2018-08-18,Home,Deportivo Alavés,3,0,W,1,5
1,2018-08-25,Away,Real Valladolid CF,1,0,W,0,18
2,2018-02-09,Home,SD Huesca,8,2,W,1,20
3,2018-09-15,Away,Real Sociedad,2,1,W,0,17
4,2018-09-23,Home,Girona FC,2,2,D,1,8
...,...,...,...,...,...,...,...,...
185,2023-05-14,Away,RCD Espanyol,4,2,W,0,12
186,2023-05-20,Home,Real Sociedad,1,2,L,1,17
187,2023-05-23,Away,Real Valladolid CF,1,3,L,0,18
188,2023-05-28,Home,RCD Mallorca,3,0,W,1,13
189,2023-04-06,Away,RC Celta,1,2,L,0,11

In [13]:
matches["target"] = (matches["Result"] == "W").astype("int")

In [14]:
matches

,Date,Location,Opponent,Goal_For,Goal_Against,Result,Venue_code,opp_code,target
0,2018-08-18,Home,Deportivo Alavés,3,0,W,1,5,1
1,2018-08-25,Away,Real Valladolid CF,1,0,W,0,18,1
2,2018-02-09,Home,SD Huesca,8,2,W,1,20,1
3,2018-09-15,Away,Real Sociedad,2,1,W,0,17,1
4,2018-09-23,Home,Girona FC,2,2,D,1,8,0
...,...,...,...,...,...,...,...,...,...
185,2023-05-14,Away,RCD Espanyol,4,2,W,0,12,1
186,2023-05-20,Home,Real Sociedad,1,2,L,1,17,0
187,2023-05-23,Away,Real Valladolid CF,1,3,L,0,18,0
188,2023-05-28,Home,RCD Mallorca,3,0,W,1,13,1
189,2023-04-06,Away,RC Celta,1,2,L,0,11,0

In [15]:
file_path = 'Dataset/Barca_Master_new.csv'
matches.to_csv(file_path, index=False)